config/routes.rb
Rails.application.routes.draw do
  
  get 'calorie_calc/index'
  
  resources :calorie_calc do
    collection do
      post 'cal_metric'
      post 'cal_imp'
    end
  end

  resources :accounts
  resources :users do
    resources :weights
    resources :foods
  end
  resources :nutrients
  resources :nutritions
  
  get 'bmi_calc/index'
  
  resources :bmi_calc do
    collection do
      post 'bmi_metric'
      post 'bmi_imp'
    end
  end
  
  controller :dashboard do
    get 'home' => :index
    get 'track' => :show
    get 'data_calories', :defaults => { :format => 'json' }
    get 'data_weights', :defaults => { :format => 'json' }
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  #controller :users do
  #  get 'edit_account' => :edit_account
  #  post 'edit_account' => :update_acccount
  #  get 'edit_profile' => :edit_profile
  #  post 'edit_profile' => :update_profile
  #end

  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    render layout: "blank"
  end
  
  def data_calories
    food = Food.new()
    now = Time.now.in_time_zone('Pacific Time (US & Canada)').to_date
    from = now  - 2.week
    i=0
    week_calories = Array.new(14)
    until from > now
      week_calories[i] = {
        "date" => from,
        "calories" => food.count_calories(current_account.get_main_user.id, from)
      }
      i+=1
      from= from+1.day
    end
    
    respond_to do |format|
      format.json {
        render :json => week_calories
      }
    end
  end
  
  def data_weights
    now = Time.now.in_time_zone('Pacific Time (US & Canada)').to_date + 2.day
    from = now - 2.weeks
    weights = Weight
      .where(:Date => (from)..(now))
      .where(:user_id => current_account.get_main_user.id )
    
    # override weights to lb if it has kg
    weights.each do |w|
      w.Weight = w.get_lb
      w.Units = "lb"
    end
    
    respond_to do |format|
      format.json {
        render :json => weights
      }
    end
  end
end

app/views/dashboard/index.html.erb
<div id="meal_tracker_intro">
  <div class="text_desc">What did you eat today?</div>
  <%= form_tag({controller: "nutritions", action: "index"}, method: "get") do %>
    <%= text_field_tag(:keyword, params[:keyword]) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

<div class="graphs">
  <div class="graph_item first">
    <div class="graph_header">Calories over lasts two weeks</div>
    <svg id="graph_calories" HEIGHT=400></svg>
  </div>
  <div class="graph_item last">
    <div class="graph_header">Weights over lasts two weeks</div>
    <svg id="graph_weights" HEIGHT=400></svg>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
        $.ajax({
           type: "GET",
           contentType: "application/json; charset=utf-8",
           url: 'data_calories',
           dataType: 'json',
           success: function (data) {
               draw_calories(data);
           },
           error: function (result) {
               error();
           }
        });
        
        $.ajax({
           type: "GET",
           contentType: "application/json; charset=utf-8",
           url: 'data_weights',
           dataType: 'json',
           success: function (data) {
               draw_weights(data);
           },
           error: function (result) {
               error();
           }
        });
    });
  </script>
</div>

<%= link_to "Calculate BMI", bmi_calc_index_path, :class => "btn btn-default" %>
<%= link_to "Daily Calorie Intake Suggestion", calorie_calc_index_path, :class => "btn btn-default" %>

app/views/dashboard/show.html.erb
<div class="track_item">
  <div class="header">Calorie Count:</div>
  <div class="details"><%= todays_calories %> kcal</div>
</div>

<% if todays_foods.any? %>
<div class="track_item">
  <div class="header">Today's Meals:</div>
  <div class="details">
    <% todays_foods.each do |x| %>
      <div class="food_item">
        <%= x["name"] %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

<% if current_weight.blank? %>
  <!-- need to put button to track weights... -->
<% else %>
<div class="track_item">
  <div class="header">Current Weight:</div>
  <div class="details"><%= current_weight %></div>
</div>
<% end %>