config/routes.rb
Rails.application.routes.draw do
  
  get 'calorie_calc/index'
  
  resources :calorie_calc do
    collection do
      post 'cal_metric'
      post 'cal_imp'
    end
  end

  resources :accounts
  resources :users do
    resources :weights
    resources :foods
  end
  resources :nutrients
  resources :nutritions
  
  get 'bmi_calc/index'
  
  resources :bmi_calc do
    collection do
      post 'bmi_metric'
      post 'bmi_imp'
    end
  end
  
  controller :dashboard do
    get 'home' => :index
    get 'track' => :show
    get 'data_calories', :defaults => { :format => 'json' }
    get 'data_weights', :defaults => { :format => 'json' }
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  #controller :users do
  #  get 'edit_account' => :edit_account
  #  post 'edit_account' => :update_acccount
  #  get 'edit_profile' => :edit_profile
  #  post 'edit_profile' => :update_profile
  #end

  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/calorie_calc_controller.rb
class CalorieCalcController < ApplicationController
  
  def index
  end
  
  def cal_metric
    
       @cal = params[:cal].to_f
       @curr_weight = params[:curr].to_f
       @targ_weight = params[:targ].to_f
       @days = params[:days].to_f

       if @targ_weight >= @curr_weight
         @result = ((@targ_weight-@curr_weight)*2.20462*3500)/@days
       else
         @result = ((@curr_weight-@targ_weight)*2.20462*3500)/@days
       end
       render :action => :index
  end
  
  def cal_imp
    
       @cal = params[:cal].to_f
       @curr_weight = params[:curr].to_f
       @targ_weight = params[:targ].to_f
       @days = params[:days].to_f

       if @targ_weight >= @curr_weight
         @res_imp = ((@targ_weight-@curr_weight)*3500)/@days
       else
         @res_imp = ((@curr_weight-@targ_weight)*3500)/@days
       end
       render :action => :index
  end
  
end

app/helpers/calorie_calc_helper.rb
module CalorieCalcHelper
end

app/views/calorie_calc/index.html.erb
<h1>Daily Calorie Intake Suggestion</h1>

<br><p style="font-size:160%">Disclaimer:</p>

 <p>This calculator does not take into consideration any amount
 of exercise that you may do as part of your daily routine.
 The calculated value is merely a suggestion and does not guarantee
 that you will hit your target weight in a given time frame.</p>
 
<br>

<br><br>

<p style="font-size:160%">Metric</p>

<%= form_tag(cal_metric_calorie_calc_index_path) do %>

  <div class="input_item"> 
      Current Calorie Intake(cal):</br> 
      <%= number_field_tag "cal", nil, min: 1, required: true %>
  </div>

  <div class="input_item"> 
      Current Weight(kg):</br> 
      <%= number_field_tag "curr", nil, min: 1, required: true %>
  </div>
  
  <div class="input_item"> 
      Target Weight(kg):</br> 
      <%= number_field_tag "targ", nil, min: 1, required: true %>
  </div>
  
  <div class="input_item"> 
      Number of Days:</br> 
      <%= number_field_tag "days", nil, min: 1, required: true %>
  </div>
  
  <div class="form_controls">
      <%= submit_tag 'Calculate' %>
  </div>

<% end %>

<br>

<% if @result.blank? %>

<% else %>

  <% if @targ_weight >= @curr_weight %>
  
    <% if @result-@cal > 3300 %>
    
      <p>That goal is unrealistic. You are trying to gain too much weight in too short a time.</p>
      
    <% else %>
    
    <p>The suggested daily calorie intake is +<ins><%= sprintf("%.1f" % @result) %></ins> calories of your current daily calorie intake.</p>
    <p>You are currently eating <ins><%= @cal %></ins> calories per day, you are suggested to eat <ins><%= sprintf("%.1f" % (@cal+@result)) %></ins>
    calories per day over the next <ins><%= @days %></ins> days to hit your target weight of <ins><%= @targ_weight %></ins> kg.</p>
    
    <% end %>
    
  <% else %>
  
    <% if @cal-@result < 1100 %>
    
      <p>That goal is unrealistic. Either your current calorie intake is not high enough to support weight loss
      or you are trying to lose too much weight in too short a time.</p>
      
    <% else %>

      <p>The suggested daily calorie intake is -<ins><%= sprintf("%.1f" % @result) %></ins> calories of your current daily calorie intake.</p>
      <p>You are currently eating <ins><%= @cal %></ins> calories per day, you are suggested to eat <ins><%= sprintf("%.1f" % (@cal-@result)) %></ins>
      calories per day over the next <ins><%= @days %></ins> days to hit your target weight of <ins><%= @targ_weight %></ins> kg.</p>
      
    <% end %>
    
  <% end %>
  
<% end %>

<br><br>

<p style="font-size:160%">Imperial</p>

<%= form_tag(cal_imp_calorie_calc_index_path) do %>

  <div class="input_item"> 
      Current Calorie Intake(cal):</br> 
      <%= number_field_tag "cal", nil, min: 1, required: true %>
  </div>

  <div class="input_item"> 
      Current Weight(lb):</br> 
      <%= number_field_tag "curr", nil, min: 1, required: true %>
  </div>
  
  <div class="input_item"> 
      Target Weight(lb):</br> 
      <%= number_field_tag "targ", nil, min: 1, required: true %>
  </div>
  
  <div class="input_item"> 
      Number of Days:</br> 
      <%= number_field_tag "days", nil, min: 1, required: true %>
  </div>
  
  <div class="form_controls">
      <%= submit_tag 'Calculate' %>
  </div>

<% end %>

<br>

<% if @res_imp.blank? %>

<% else %>

  <% if @targ_weight >= @curr_weight %>
  
    <% if @res_imp-@cal > 3300 %>
    
      <p>That goal is unrealistic. You are trying to gain too much weight in too short a time.</p>
      
    <% else %>
    
    <p>The suggested daily calorie intake is +<ins><%= sprintf("%.1f" % @res_imp) %></ins> calories of your current daily calorie intake.</p>
    <p>You are currently eating <ins><%= @cal %></ins> calories per day, you are suggested to eat <ins><%= sprintf("%.1f" % (@cal+@res_imp)) %></ins>
    calories per day over the next <ins><%= @days %></ins> days to hit your target weight of <ins><%= @targ_weight %></ins> lb.</p>
    
    <% end %>
    
  <% else %>
  
    <% if @cal-@res_imp < 1100 %>
    
      <p>That goal is unrealistic. Either your current calorie intake is not high enough to support weight loss
      or you are trying to lose too much weight in too short a time.</p>
      
    <% else %>

      <p>The suggested daily calorie intake is -<ins><%= sprintf("%.1f" % @res_imp) %></ins> calories of your current daily calorie intake.</p>
      <p>You are currently eating <ins><%= @cal %></ins> calories per day, you are suggested to eat <ins><%= sprintf("%.1f" % (@cal-@res_imp)) %></ins>
      calories per day over the next <ins><%= @days %></ins> days to hit your target weight of <ins><%= @targ_weight %></ins> lb.</p>
      
    <% end %>
    
  <% end %>
  
<% end %>