config/routes.rb
Rails.application.routes.draw do
  
  get 'calorie_calc/index'
  
  resources :calorie_calc do
    collection do
      post 'cal_metric'
      post 'cal_imp'
    end
  end

  resources :accounts
  resources :users do
    resources :weights
    resources :foods
  end
  resources :nutrients
  resources :nutritions
  
  get 'bmi_calc/index'
  
  resources :bmi_calc do
    collection do
      post 'bmi_metric'
      post 'bmi_imp'
    end
  end
  
  controller :dashboard do
    get 'home' => :index
    get 'track' => :show
    get 'data_calories', :defaults => { :format => 'json' }
    get 'data_weights', :defaults => { :format => 'json' }
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  #controller :users do
  #  get 'edit_account' => :edit_account
  #  post 'edit_account' => :update_acccount
  #  get 'edit_profile' => :edit_profile
  #  post 'edit_profile' => :update_profile
  #end

  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/nutrient.rb
class Nutrient < ActiveRecord::Base
  belongs_to :food
  validates :ref_id, presence: true, numericality: true
  validates :name, presence: true
  validates :value, numericality: {greater_than_or_equal_to: 0 }
end

app/controllers/nutrients_controller.rb
class NutrientsController < ApplicationController
  before_action :set_nutrient, only: [:show, :edit, :update, :destroy]

  # GET /nutrients
  # GET /nutrients.json
  def index
    @nutrients = Nutrient.all
  end

  # GET /nutrients/1
  # GET /nutrients/1.json
  def show
  end

  # GET /nutrients/new
  def new
    @nutrient = Nutrient.new
  end

  # GET /nutrients/1/edit
  def edit
  end

  # POST /nutrients
  # POST /nutrients.json
  def create
    @nutrient = Nutrient.new(nutrient_params)

    respond_to do |format|
      if @nutrient.save
        format.html { redirect_to @nutrient, notice: 'Nutrient was successfully created.' }
        format.json { render :show, status: :created, location: @nutrient }
      else
        format.html { render :new }
        format.json { render json: @nutrient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nutrients/1
  # PATCH/PUT /nutrients/1.json
  def update
    respond_to do |format|
      if @nutrient.update(nutrient_params)
        format.html { redirect_to @nutrient, notice: 'Nutrient was successfully updated.' }
        format.json { render :show, status: :ok, location: @nutrient }
      else
        format.html { render :edit }
        format.json { render json: @nutrient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutrients/1
  # DELETE /nutrients/1.json
  def destroy
    @nutrient.destroy
    respond_to do |format|
      format.html { redirect_to nutrients_url, notice: 'Nutrient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nutrient
      @nutrient = Nutrient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nutrient_params
      params.require(:nutrient).permit(:ref_id, :name, :group, :unit, :value, :food_id)
    end
end

app/helpers/nutrients_helper.rb
module NutrientsHelper
end

app/views/nutrients/_form.html.erb
<%= form_for(@nutrient) do |f| %>
  <% if @nutrient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nutrient.errors.count, "error") %> prohibited this nutrient from being saved:</h2>

      <ul>
      <% @nutrient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref_id %><br>
    <%= f.text_field :ref_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nutrients/edit.html.erb
<h1>Editing Nutrient</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutrient %> |
<%= link_to 'Back', nutrients_path %>

app/views/nutrients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nutrients</h1>

<table>
  <thead>
    <tr>
      <th>Ref</th>
      <th>Name</th>
      <th>Group</th>
      <th>Unit</th>
      <th>Value</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nutrients.each do |nutrient| %>
      <tr>
        <td><%= nutrient.ref_id %></td>
        <td><%= nutrient.name %></td>
        <td><%= nutrient.group %></td>
        <td><%= nutrient.unit %></td>
        <td><%= nutrient.value %></td>
        <td><%= nutrient.food %></td>
        <td><%= link_to 'Show', nutrient %></td>
        <td><%= link_to 'Edit', edit_nutrient_path(nutrient) %></td>
        <td><%= link_to 'Destroy', nutrient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nutrient', new_nutrient_path %>

app/views/nutrients/new.html.erb
<h1>New Nutrient</h1>

<%= render 'form' %>

<%= link_to 'Back', nutrients_path %>

app/views/nutrients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ref:</strong>
  <%= @nutrient.ref_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @nutrient.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @nutrient.group %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @nutrient.unit %>
</p>

<p>
  <strong>Value:</strong>
  <%= @nutrient.value %>
</p>

<p>
  <strong>Food:</strong>
  <%= @nutrient.food %>
</p>

<%= link_to 'Edit', edit_nutrient_path(@nutrient) %> |
<%= link_to 'Back', nutrients_path %>