config/routes.rb
Rails.application.routes.draw do
  
  get 'calorie_calc/index'
  
  resources :calorie_calc do
    collection do
      post 'cal_metric'
      post 'cal_imp'
    end
  end

  resources :accounts
  resources :users do
    resources :weights
    resources :foods
  end
  resources :nutrients
  resources :nutritions
  
  get 'bmi_calc/index'
  
  resources :bmi_calc do
    collection do
      post 'bmi_metric'
      post 'bmi_imp'
    end
  end
  
  controller :dashboard do
    get 'home' => :index
    get 'track' => :show
    get 'data_calories', :defaults => { :format => 'json' }
    get 'data_weights', :defaults => { :format => 'json' }
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  #controller :users do
  #  get 'edit_account' => :edit_account
  #  post 'edit_account' => :update_acccount
  #  get 'edit_profile' => :edit_profile
  #  post 'edit_profile' => :update_profile
  #end

  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  has_many :users, dependent: :destroy
  
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\z/i
  validates :email, uniqueness: true, format: EMAIL_REGEX
  
  def email=(val)
    write_attribute(:email, val.downcase)
  end
  
  def get_users
    return User.where(:account_id => self.id).order("is_main DESC, first_name ASC, last_name ASC")
  end
  
  def get_main_user
    return User.where(:account_id => self.id, :is_main => 1).first
  end
  
  def get_other_users
    return User.where(:account_id => self.id, :is_main => 0).order("first_name ASC, last_name ASC")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authorize
  skip_before_filter :check_profile
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  
  def index
    @accounts = Account.all
  end
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @users = User.where(:account_id => current_account.id, :is_main => 0)
  end

  # GET /accounts/new
  def new
    @account = Account.new
    render layout: "simple"
  end

  # GET /accounts/1/edit
  def edit
    render layout: "modal"
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        session[:account_id] = @account.id
        @account.users.create(:is_main => 1, :gender => 3, :birth => "")
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @account }
      else
        if @account.errors.any?
          flash.now[:error] = []
          for message_error in @account.errors.full_messages
            flash.now[:error] << message_error
          end
        end
        format.html { render :new, layout: "simple" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_account
      if current_account.get_main_user != nil
        @main_user = current_account.get_main_user
      else
        @main_user = User.new
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <div class="well">
    
    <div class="input_item"> 
      Email:</br> 
      <%= f.text_field :email %> 
    </div>
    
    <div class="input_item"> 
      Password:</br> 
      <%= f.password_field :password %>
    </div>
    
    <div class="input_item"> 
      Confirmation:</br> 
      <%= f.password_field :password_confirmation %>
    </div>
    
    <div class="form_controls">
      <%= f.submit 'Register' %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for :title do %>
  Update Account
<% end %>

<%= render 'form' %>

<% content_for :footer do %>
  <button class="btn btn-primary" onclick="submit_account_form('edit')">Submit</button>
<% end %>

app/views/accounts/index.html.erb
<h1>Listing Accounts</h1>

<table border="1" style="width:100%">
  <thead>
    <tr>
      <th style="padding:10px">Email</th>
      <th style="padding:10px">Password</th>
      <th style="padding:10px" colspan="3">Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td style="padding:10px"><%= account.email %></td>
        <td style="padding:10px"><%= account.password_digest %></td>
        <td style="padding:10px"><%= link_to 'Show', account %></td>
        <td style="padding:10px"><%= link_to 'Edit', edit_account_path(account) %></td>
        <td style="padding:10px"><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<div id="register_form">
<%= render 'form' %>
<%= link_to 'Back', login_path %>
</div>

app/views/accounts/show.html.erb
<div class="profile_container">
  <div class="list_header">
    Account
  </div>
  <div class="list with_header">
    <div class="item last">
      <div class="desc">
        <span class="data">
          Email:
        </span><br />
        <%= @account.email %>
      </div>
    </div>
  </div>
</div>

<% if current_account.get_main_user == nil %>
  <div class="list_header">
    Profile
  </div>
  <div class="error_list with_header">
    <div class="item">
      Please proceed with setting up your main profile<br /><br />
      <%= link_to 'Add', new_user_path, class: "btn btn-default", data: {toggle: "modal", target: "#my-modal" } %>
    </div>
  </div>
<% else %>
  <div class="profile_container">
    <div class="list_header">
      Main Profile
      <%= link_to 'Edit', edit_user_path(@main_user), class: "btn btn-default btn-xs", data: {toggle: "modal", target: "#my-modal" } %>
    </div>
    <div class="list with_header">
      <div class="item">
        <div class="desc">
          <span class="data">
            Name:
          </span><br />
          <%= @main_user.full_name %>
        </div>
      </div>
      <div class="item">
        <div class="desc">
          <span class="data">
            Gender:
          </span><br />
          <%= @main_user.gender_desc %>
        </div>
      </div>
      <div class="item">
        <div class="desc">
          <span class="data">
            Birth Date:
          </span><br />
          <%= @main_user.birth %>
        </div>
      </div>
      <div class="item last">
        <div class="desc">
          <span class="data">
            Age:
          </span><br />
          <%= @main_user.age %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="profile_container">
    <div class="list_header">
      Others
      <%= link_to 'Add', new_user_path, class: "btn btn-default btn-xs", data: {toggle: "modal", target: "#my-modal" } %>
    </div>
    <% if @users.empty? %>
      <div class="error_list with_header">
        <div class="item">
          You do not have any user record
        </div>
      </div>
    <% else %>
      <div class="list with_header">
        <% @users.each do |user| %>
          <% 
            if user == @users.last
              c = " last"
            else
              c = ""
            end
          %>
          <div class="item<%= c %>">
            <div class="desc">
              <%= user.full_name %>
              <span>
                (<%= user.gender_desc %>, <%= user.age %>)
              </span>
            </div>
            <%= link_to 'Destroy', user, method: :delete, :class => "btn btn-default btn-xs", data: { confirm: 'Are you sure?' } %>
            <%= link_to 'Edit', edit_user_path(user), :class => "btn btn-default btn-xs", data: {toggle: "modal", target: "#my-modal" } %>
          </div>
        <% end %>
        
      </div>
    <% end %>
  </div>
<% end %>